### ISSUE TITLE
Oefenzitting 7

### ISSUE THREAD

**Issue by warreee** [KULeuven-DeptCW/AaC-Exc#10]
In oefenzitting 7 die we van professor Demoen kregen waren er nog 2 extra oefeningen 7 en 8 voorzien dacht ik?

**Comment by KommuSoft** [comment]
Deze oefeniningen zijn er enkele jaren geleden uit gehaald... Omdat ze nogal moeilijk waren (op basis van feedback van studenten), en we dit "niveau" niet van "alle" studenten kunnen verwachten. (voel u vooral niet beledigd)

Eventueel wil ik proberen na de kantooruren hier oplossingen voor te voorzien, het enige dilemma die dan nog overblijft is dat de opgave niet meer synchroon verloopt met de oplossingen.

Any comment?

**Comment by warreee** [comment]
Geen probleem dan hoor, hou de oefenzittingen dan maar gewoon synchroon ;)
