### ISSUE TITLE
Tekst primitief recursieve functies

### ISSUE THREAD

**Issue by KommuSoft** [KULeuven-DeptCW/AaC-Exc#13]
Is de tekst die u ons aanraadde van Frederik over primitief recursieve functies toegelaten op het examen?

**Comment by KommuSoft** [comment]
Op de tussentijdse toets helaas niet, dit zijn helaas de regels en het
is (een jaar) te laat om die nog aan te passen.

Wat betreft het examen zelf ken ik de regeling niet precies? Ik zal
het aan prof. Demoen vragen.

**Comment by warreee** [comment]
Moet ik mijn mail die ik nog gestuurd heb anders als een issue openen?

**Comment by KommuSoft** [comment]
> Moet ik mijn mail die ik nog gestuurd heb anders als een issue openen?

Ik heb het hieronder toegevoegd. Het is de bedoeling om GitHub ook te gebruiken voor open (maar anonieme) briefwisseling. Op die manier wordt niemand bevoordeeld (no offense) tegenover iemand anders (dit staat zelfs in het examenreglement, maar wordt blijkbaar door surveillanten niet altijd grondig gevolgd).

> Het examen in januarie is gesloten boek, dus daar is het zeker niet van toepassing.
> Ok spijtig, maar een andere cursustekst over automaten en berekenbaarheid is toch wel toegelaten? Dit was allesinds toegestaan vorige keer op het tussentijdsexamen.

Ja, dat is wel toegelaten.
