### ISSUE TITLE
Regular_TM

### ISSUE THREAD

**Issue by warreee** [KULeuven-DeptCW/AaC-Exc#14]
Klopt als ik over de machine H_s in st 3.11.2 het volgende zeg:

L(H_s) = {0^n 1^n} als H_s de string s niet accepteert?

**Comment by KommuSoft** [comment]
Dat **klopt niet**. Maar waarschijnlijk wil je zeggen:

> L(H_s) = {0^n 1^n} als **M** de string s niet accepteert?

In het geval M wel accepteert is de taal:

L(H_s)=\Sigma^*

Merk op dat we immers **niet** `x` op `M` laten lopen, maar `s`. We hebben dus `s` "gehardwired".

In het eerste geval is de taal dus niet regulier, in het tweede geval wel.

**Comment by warreee** [comment]
Inderdaad ik bedoelde het andere.
Merci
