### ISSUE TITLE
Bewijs pompend lemma reguliere talen

### ISSUE THREAD

**Issue by warreee** [KULeuven-DeptCW/AaC-Exc#15]
Er staat in dit bewijs dat de accepterende sequentie van toestanden strikt groter is als d.
Waarom moet dit strikt groter zijn en niet groter of gelijk aan?

**Comment by warreee** [comment]
Ik denk dat ik het weet, de lengte van een zo'n sequentie is altijd minsten 1 groter als het aantal symbolen in de string, niet?

**Comment by KommuSoft** [comment]
Inderdaad: stel dat de string `s=s_1s_2s_3s_4` is, dan zijn de toestanden om dit te beslissen: `h_0h_1h_2h_3h_4` (hier heb ik `h` gebruikt omdat twee verschillende `h`'s wel op eenzelfde `q` (toestand) kunnen slaan, er kan dus staan `q_0q_2q_2q_1q_3` bijvoorbeeld). Je start dus in een eerste toestand `h_0=q_s` alvorens een karakter in te lezen van de string.

**Comment by warreee** [comment]
Ok merci voor de uitleg.
