### ISSUE TITLE
Elke CFL is herkenbaar

### ISSUE THREAD

**Issue by warreee** [KULeuven-DeptCW/AaC-Exc#16]
Om dit bewijzen:

Is het voldoende om zeggen dat we alle strings die gegeneerd worden door de CFG van de gegeven CFL, geven aan een TM die de overeenkomstige PDA van de CFL simuleert, enzo afleiden of de we de CFL herkennen?

Indien dit niet voldoende zou zijn, moet ik dan eerst een beslisser maken die gebruik maakt van het feit dat A_CFG beslisbaar is?

**Comment by KommuSoft** [comment]
Wel **voor elke** CFL bestaat er een overeenkomstige CFG en PDA. Een Turing machine kan zo'n PDA simuleren, door dus bij een _push_ te schrijven op de tape en naar rechts te bewegen en bij een _pop_ naar links te bewegen en het karakter uit te lezen (maar de PDA kan dus niet in de "geschiedenis" van de stapel gaan zoeken zonder de bovenliggende karakters te verwijderen). We kunnen dus zo aantonen, dat voor elke PDA er een TM bestaat die net dezelfde taal beslist (we hebben dus een beslisser geconstrueerd).

Elke beslisbare taal is zowel herkenbaar als co-herkenbaar, dus is de stelling _"Elke CFL is herkenbaar"_ een logisch gevolg.

**Comment by warreee** [comment]
Ok Thanks!
