### ISSUE TITLE
L(M) is recognized by a TM having even number of states

### ISSUE THREAD

**Issue by warreee** [KULeuven-DeptCW/AaC-Exc#17]
Ik heb gevonden op internet dat dit een triviale eigenschap is.
Komt dit doordat een TM machine met oneven aantal staten steeds kan omgevormd worden naar een TM met een even aantal staten? Hoe gebeurt dit dan?
Als dat zo is dan kunnen we toch gewoon zeggen dat Neg_P leeg is en vandaar de trivialiteit veronderstel ik?

**Comment by ingdas** [comment]
Er is idd altijd een transformatie van een TM met oneven -> even toestanden. 
Je voegt gewoon een onbereikbare toestand toe, die je niet gebruikt, of je zet een toestand, die niets doet, voor je starttoestand, en alles is opgelost.

Je laatste zin is idd correct

**Comment by warreee** [comment]
Ok Thanks
