### ISSUE TITLE
Oefenzitting 1 oef 2 nr 4

### ISSUE THREAD

**Issue by warreee** [KULeuven-DeptCW/AaC-Exc#2]
Bij deze oefening wordt:
0\* |1\* | 0 (0|1)\* 0 |1 (0|1)\* 1
als antwoord gegeven.

De strings 10101 of 01010 bevatten beide evenveel de substring 01 en 10:
- 10 10 1 en 1 01 01
- 01 01 0 en 0 10 10
  Maar bovenstaande reguliere expressie kan deze toch niet genereren?

**Comment by KommuSoft** [comment]
De disjunctie bindt minder sterk dan de concatenatie of de Kleene ster. Dus staat er:
- 0*, of
- 1*, of
- 0(0|1)*0, of
- 1(0|1)*1.

10101 kan gegenereerd worden met geval 4, 01010 kan gegenereerd worden met geval 3. Men kan immers in een Kleene ster altijd **opnieuw** kiezen hoe men dit matched. Als we de haakjes overnemen staat er dus:

```
1(0)(1)(0)1
0(1)(0)(1)0
```

**Comment by warreee** [comment]
Ah, ok ik zie het. Ik dacht inderdaad verkeerd, dat eens je bij de Kleene ster gekozen hebt, je dit altijd opnieuw moest gebruiken. Bedankt.
