### ISSUE TITLE
Apart compileren

### ISSUE THREAD

**Issue by warreee** [KULeuven-DeptCW/AaC-Exc#7]
Als ik een bestend apart wil compileren bvb met texmaker moet ik de lijn
\usepackage[backend=biber]{biblatex}
toevoegen. Bestaat hier geen andere manier voor?

**Comment by KommuSoft** [comment]
Waarschijnlijk heb je `bibtex` niet geïnstalleerd. Je kan ook de `makepdf.sh` aanpassen: immers bevatten de oefeningen geen bibliografie. Het is een algemeen script om zowat elke `.tex` file te compileren.
